sudo: no
addons:
  postgresql: "9.3"
language: python
env:
  - TOXENV=py27-tests
  - TOXENV=py34-flake8
  - TOXENV=py34-isort
install:
  - pip install coveralls tox
before_script:
script:
  - tox
after_success: coveralls
notifications:
