sudo: no
addons:
  postgresql: "9.3"
language: python
env:
  - TOXENV=py27-tests
  - TOXENV=py27-isort
install:
  - pip install -r requirements.txt
  - pip install coveralls tox
before_script:
script:
  - tox
after_success: coveralls
notifications:
    email: false

